name: Feature Request
description: Suggest an idea for slash-exit
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Please fill out the information below to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I've also thought about...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Animation/Visual Enhancement
        - Shell Integration
        - Configuration/Customization
        - Performance Improvement
        - Cross-platform Support
        - Other (please specify in additional context)
    validations:
      required: true

  - type: checkboxes
    id: scope
    attributes:
      label: Scope
      description: How would you categorize this feature?
      options:
        - label: This is a breaking change
        - label: This would require documentation updates
        - label: This might affect existing installations

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request here.
      placeholder: Any additional information that might help us understand your request